### ISSUE TITLE
Incorrect dependencies for v2 series (at least)

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/pmdarima-feedstock#38]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I've looked at several instances of pmdarima >=2.0.0, and in almost all of them, there are incorrect dependencies, as compared with the [requirements.txt file in the pmdarima repo](https://github.com/alkaline-ml/pmdarima/blob/v2.0.0/requirements.txt).  In particular, the numpy version in this package is higher than in the repo's requirements.txt, and the statsmodels version is not high enough.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by DManowitz** [comment]
@tomasvanpottelbergh @cdesouza21 This issue is continuing, and I think it has to do with the use of `{{ pin_compatible('numpy') }}` in the meta.yaml.  According to [this post](https://github.com/conda-forge/conda-forge.github.io/issues/2037), it appears that this method of pinning should no longer be used.

**Comment by tomasvanpottelbergh** [comment]
@DManowitz Sorry, but I'm not using this package any more myself and don't really have the time to maintain it. I'm happy to merge a PR fixing the issue or add other people as maintainers.

**Comment by DManowitz** [comment]
> @DManowitz Sorry, but I'm not using this package any more myself and don't really have the time to maintain it. I'm happy to merge a PR fixing the issue or add other people as maintainers.

@tomasvanpottelbergh Pushed a PR.  Hopefully, this fixes the issue.
